# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_something": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://fastai.github.io/testnote/"

git_url = "https://github.com/fastai/testnote/tree/master/"

def custom_doc_links(name): return None
