# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['say_something']

# Cell

def say_something(msg):
    """This is my first function"""

    print(msg)