# AUTOGENERATED! DO NOT EDIT! File to edit: 01_data.ipynb (unless otherwise specified).

__all__ = ['get_months', 'get_names']

# Cell

def get_months():
    """Returns all months of the year"""

    return list(range(1, 12))

# Cell
def get_names():
    """Returns a list of names"""
    return ["Ozzy", "Tony", "Geezer", "Bill"]